#!/usr/bin/env bash
# Regenerate PHP model classes from the vendored OpenAPI spec.
# Run: composer codegen
#
# Uses @openapitools/openapi-generator-cli v2.39 in Docker mode (no local Java needed).
# Generator version and Docker settings are in openapitools.json.
# Docker image openapitools/openapi-generator-cli:v7.9.0 must be available locally
# or pullable from Docker Hub.
#
# When generation completes, review the diff in src/Generated/ carefully:
#   - Ensure namespace matches GoPay\Payments\Generated\Model
#   - Ensure ModelInterface.fromArray(array): static is preserved
#
# The entire src/Generated/ directory is excluded from PHPStan analysis (phpstan.neon).

set -euo pipefail
cd "$(dirname "$0")/.."

TMP_DIR=".codegen-tmp"
GEN_DIR="src/Generated"

# FETCH_SPEC_URL is the beta pre-release feed — ahead of the public docs, used as the
# source of truth for generation so models don't lag behind the real API.
# STAMP_SPEC_URL is what gets written into every generated file's header comment instead.
# This repo is mirrored to GitHub and published on Packagist, so that comment is public;
# stamping the beta URL would ship every consumer a link they can't actually open.
# The two will differ until the public docs catch up with the beta feed.
FETCH_SPEC_URL="https://payments-api.beta.gopay.com/spec/en/payments.yaml"
STAMP_SPEC_URL="https://api-docs.gopay.com/spec/en/payments.yaml"

echo "→ Fetching latest spec from payments-api.beta.gopay.com ..."
curl -fsSL "$FETCH_SPEC_URL" -o spec/payments.yaml

# The beta deployment injects a Prism mock server as the FIRST servers entry; the
# canonical spec (api-docs.gopay.com) lists only Sandbox and Production. Shipping it
# would leave servers[0] pointing at a mock host in a published SDK, so strip it.
echo "→ Stripping the beta-injected mock server from servers ..."
python3 - <<'PY'
import pathlib
import re
import sys

path = pathlib.Path("spec/payments.yaml")
text = path.read_text(encoding="utf-8")

# One servers list item: the "- url:" line plus its indented continuation lines.
# The url may be single-quoted, double-quoted or bare, so match all three.
pattern = re.compile(
    r"\n  - url:[ \t]*['\"]?[^\n'\"]*payments-api-mock[^\n'\"]*['\"]?[^\n]*\n(?:    [^\n]*\n)*",
)
text, count = pattern.subn("\n", text)
if count:
    path.write_text(text, encoding="utf-8")
print(f"   removed {count} mock server entr{'y' if count == 1 else 'ies'}")

# Fail closed: if the strip missed a form we did not anticipate, stop rather than
# generate — shipping a vendored spec pointing at a mock host is the bug we are
# preventing, and a silent no-op here is how it would come back.
if "payments-api-mock" in path.read_text(encoding="utf-8"):
    sys.exit(
        "   ERROR: payments-api-mock still present in spec/payments.yaml after stripping.\n"
        "   The beta feed changed the shape of this entry — update the pattern in scripts/codegen.sh."
    )
PY

echo "→ Generating PHP models from spec/payments.yaml ..."

# The CLI reads openapitools.json for generator config and Docker settings.
# useDocker:true causes it to volume-mount spec/ and .codegen-tmp into the container.
npx @openapitools/openapi-generator-cli@2.39.0 generate

rm -rf "$GEN_DIR"
mkdir -p "$GEN_DIR"

if [ -d "$TMP_DIR/lib/Model" ]; then
  cp -r "$TMP_DIR/lib/Model" "$GEN_DIR/"
fi
for f in ObjectSerializer.php ModelInterface.php HeaderSelector.php; do
  if [ -f "$TMP_DIR/lib/$f" ]; then
    cp "$TMP_DIR/lib/$f" "$GEN_DIR/"
  fi
done

rm -rf "$TMP_DIR"

echo "→ Stamping generated files with spec URL ..."
find "$GEN_DIR" -name "*.php" | while read -r file; do
  awk -v spec="$STAMP_SPEC_URL" \
    'NR==1{print; print "// @generated from " spec; print "// Do not edit this file — report issues to the upstream spec, not here."; next}1' \
    "$file" > "$file.tmp" && mv "$file.tmp" "$file"
done

echo "✓ Codegen complete → $GEN_DIR"
